name: run-tests
on: [workflow_dispatch]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: install djangorestframework dependency
        run: pip install djangorestframework
      - name: install coverage dependency
        run: pip install coverage
      - name: run tests
        run: python manage.py test
      - name: generate .coverage file for next step
        run: coverage run manage.py test
      - name: Show how much code is covered by tests
        run: coverage report